# Настройки ORM
datasource:
  # Задаём базу данных, к которой будет происходить подключение
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
#    username: ${PGUSER}
    username: "postgres"
#    password: ${PGPASSWORD}
    password: "X6I7PUMjtkBVqoWpgLzV"
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    url: "jdbc:postgresql://containers-us-west-116.railway.app:6124/railway"

# Заполняем базу данных первоначальными данными
ebean:
  migration:
    run: true
